### ISSUE TITLE
Master delete page

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/AMS-with-TimeTable#101]
Create a page where I can delete entries in the table by code. 

One input field as "code"

Below there has to be a table 

1) delete sem (from addsem table it should delete all entries of code) 
2) delete faculty (from addfaculty table it should delete all entries of code) 
3) delete room (from add room table)
4) delete saved timetable data (from classtimetable table) 
5) delete locked timetable data (from locked timetable) 
6) delete timetable (from timetable table)

One more Button at the top to delete everything with name "Delete All"

Whereever they click delete there has to be a confirmation wether you want to delete? Are you  sure?

**Comment by pihu24** [comment]
done in recent PR
