### ISSUE TITLE
Front end page for common load

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/AMS-with-TimeTable#136]
Faculty: it has to be check box similar to add faculty page. 

Subcode: Dropdown from add subject table. 

Sub fullname and SubName has to be fetched automatically once the sub code is selected. 

Hrs: numbers 

Code: has to be fetched from current url

When we click submit button, for each faculty, one object has to be created. These values are to be shown in table below with edit and delete options

**Comment by Akshikagarg** [comment]
Completed
