### ISSUE TITLE
Invitation mail link

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/AMS-with-TimeTable#409]
In the invitation mail, the link for acceptance or rejection has to be added.

The url for this page shall be \prm\:eventId\reviewer\:userId

In this page, we should show event name, date and accept or reject buttons.

When the user clicks accept, it should make a post requrest to events table. In that table, there is a reviewerschema where status has to be updated.

**Comment by SumitTeerthani** [comment]
Completed the task

**Comment by harimurugan1989** [comment]
Not completed.
