### ISSUE TITLE
Merge paper data in the paper tab of editor dashboard

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/AMS-with-TimeTable#412]
Fetch the paper data from the paper table in the backend using eventId.

Use chakra Ui table to show the data in the front end. For time being show the following data in the form of table.

1) Paper Title
2) Authors
3) version
4) paperlink

**Comment by Luson045** [comment]
fetched the all the paper data from the entries in paper table in backend having the event id as that of the url parameter.
