### ISSUE TITLE
Assign a reviewer to the paper. 

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/AMS-with-TimeTable#418]
In the same page of all papers.jsx. We need to assign reviewers to a particular paper. 

You need to make a post request to a particular paper (paperid) with a array of reviewer. 

This reviewer list can be obtained from the event table. 

Basically we are trying to assign reviewer/reviewers to a paper.

**Comment by Luson045** [comment]
added a feature to assign event reviewers to certain papers
