### ISSUE TITLE
Merging new submission with backend. 

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/AMS-with-TimeTable#427]
Make post req from front-end to post a paper details from the front end page. 

This page in the front-end can be found at /prm/home 

In the side bar under author, there is a new submission tab. First we need to select the event and in the redirected page we need to write the post request. It is similar to what you have done in paper details. Here we need to save all the details such as authors. Titles, for upload we will be saving the link.

**Comment by Luson045** [comment]
Sir, there's no one named ARCHIT in reviewmodule team.

**Comment by Luson045** [comment]
merger new paper submissions with backend

**Comment by harimurugan1989** [comment]
This is different. You can work on this next

**Comment by harimurugan1989** [comment]
when i click add author, it is creating new user but it is not getting added to the table list. 

Also if the user is already there, then you can skip the user creation step
