### ISSUE TITLE
Multiform design

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/AMS-with-TimeTable#489]
This multi form has different components and each of them need to be designed seperately. 

All functionality for the form is already done. Only UI needs to be modified/improved. 

Link can be obtained at 

/prm/:eventId/newpaper 

The form will move to next step upon filling the first step.

**Comment by Jagjit0306** [comment]
![image](https://github.com/xceed-nitj/AMS-with-TimeTable/assets/146818104/9834b7cf-4ade-4271-b4d4-de76a8a926ea)

I cannot access that page
