### ISSUE TITLE
Sidebar responsiveness 

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/AMS-with-TimeTable#490]

**Comment by harimurugan1989** [comment]
Still some improvments are required

**Comment by Akdest** [comment]
Sir where we r facing problem

**Comment by harimurugan1989** [comment]
![Screenshot_20240617_140341_Chrome.jpg](https://github.com/xceed-nitj/AMS-with-TimeTable/assets/88608850/199b7d8c-0ddc-444b-9aba-3e1e22ca58e9)


Default menu is not completely visible. 

In desktop, the sidebar size has been increased and subheadings are right alligned which is not looking food. Previous set ups can be kept for desktop and make changes only in mobile
