### ISSUE TITLE
Add track improvements 

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/AMS-with-TimeTable#538]
-Change the font color of delete button to white 
-Add a warning before deleting. It can ask "Are you sure whether item can be deleted" It shall show Yes and Cancel button. Upon clicking yes it can delete 

Follow these in all the pages where delete is there. If you want sample code for this. You can check any addsem.jsx page in timetable module.

**Comment by gurshaan17** [comment]
I sent this pr in morning forgot to cancel it
