### ISSUE TITLE
Navbar loading time

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/AMS-with-TimeTable#600]
Currently navbar takes some time to load. can we load the navbar directly and then load the contents based on login in some time. i think currently it is checking for the logged in user and then loads the navbar.

**Comment by gurshaan17** [comment]
https://github.com/xceed-nitj/AMS-with-TimeTable/assets/140047039/324c93a5-f752-4e29-8da8-69e4c4b87378

I tried solving it . is it fine?
