### ISSUE TITLE
Create front end page for note 

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/AMS-with-TimeTable#79]
This is add note page: 

Sem: It has to be dropdown and filtered from the existing code 
Faculty: from the existing faculty corresponding to code (faculty shall be in any sem. All ready route is there. Chk addfaculty/all)
Note: text field in the form of array. Similar to faculty added to semester. Here note can be added to sem. 

Code: it  has to be fetched from current URL while making post request

Show table similar to add faculty page

**Comment by Akshikagarg** [comment]
completed
