### ISSUE TITLE
Prevent duplicate entry in add faculty and add room

### ISSUE THREAD

**Issue by harimurugan1989** [xceed-nitj/AMS-with-TimeTable#83]
pihu has completed this function for add subject page. use similar function here to complete it

**Comment by pihu24** [comment]
done

**Comment by harimurugan1989** [comment]
<img width="960" alt="image" src="https://github.com/xceed-nitj/AMS-with-TimeTable/assets/88608850/791f8313-a1ee-402e-8a6d-db534f1d0d96">

its not working. check once. i simply clicked twice
